### ISSUE TITLE
How to make timp faster to communicate a thread?

### ISSUE THREAD

**Issue by tumashu** [mola-T/thread#4]
1. test.el file:

```
(defun test ()
  (setq test1 (number-sequence 1 100000)))

(defun print-test ()
  (format "%s" (pop test1)))

(provide 'test)

```
1. timp code

```
(require 'timp)

(setq pyim-thread1 (timp-get :persist t))
(timp-require-package pyim-thread1 'test)
(timp-send-exec pyim-thread1 'test)
(benchmark 10000 '(timp-send-exec pyim-thread1 'print-test))
```

The result is：  "Elapsed time: 3.837000s (0.358000s in 7 GCs)"

I want to  the time is < 0.5, is it possible?

**Comment by mola-T** [comment]
I think it is impossible.

The `benchmark` you ran was counting the time for queuing the 10000 jobs but not the time  for running the functions. It is very inefficient to send many easy jobs to threads. It is designed to handle jobs but not handle request.

**Comment by tumashu** [comment]
Well , thanks for your reply!
